package com.example.util

import com.example.data.model.BotFile
import com.example.data.model.BotLanguage
import com.example.data.model.BotProject

data class AutoFixResult(
    val fixedCode: String,
    val fixesApplied: List<String>,
    val wasModified: Boolean
)

data class ProjectAutoFixReport(
    val updatedFiles: List<BotFile>,
    val fixesApplied: List<String>,
    val addedFileCount: Int
)

/**
 * Enterprise Bot Code Auto-Fixer & Optimizer.
 * Inspects imported bot scripts and automatically:
 * 1. Corrects outdated Discord.js (v11/v12/v13 -> v14+ with GatewayIntentBits & EmbedBuilder).
 * 2. Injects missing Discord.py 2.0+ intents (message_content = True).
 * 3. Adds missing client.login() / bot.run() calls with token fallbacks.
 * 4. Adds missing client.once('ready') and messageCreate command routers.
 * 5. Adds bot self-response guards (if (message.author.bot) return).
 * 6. Fixes unclosed brackets and syntax slips.
 * 7. Automatically generates missing .env, package.json, requirements.txt, and README.md.
 */
object BotCodeAutoFixer {

    fun autoFixFile(
        rawCode: String,
        filePath: String,
        project: BotProject? = null
    ): AutoFixResult {
        var code = rawCode
            .removePrefix("\uFEFF")
            .replace("\r\n", "\n")
            .replace("\r", "\n")

        val fixes = mutableListOf<String>()
        val ext = filePath.substringAfterLast('.', "").lowercase()

        when (ext) {
            "js", "mjs", "cjs", "ts", "jsx", "tsx" -> {
                val res = fixJavaScriptDiscordCode(code, filePath, project)
                code = res.fixedCode
                fixes.addAll(res.fixesApplied)
            }
            "py", "pyw" -> {
                val res = fixPythonDiscordCode(code, filePath, project)
                code = res.fixedCode
                fixes.addAll(res.fixesApplied)
            }
            "json" -> {
                val res = fixJsonCode(code)
                code = res.fixedCode
                fixes.addAll(res.fixesApplied)
            }
            "env" -> {
                val res = fixEnvCode(code, project)
                code = res.fixedCode
                fixes.addAll(res.fixesApplied)
            }
        }

        return AutoFixResult(
            fixedCode = code,
            fixesApplied = fixes,
            wasModified = fixes.isNotEmpty() || code != rawCode
        )
    }

    fun autoFixProject(
        project: BotProject,
        files: List<BotFile>
    ): ProjectAutoFixReport {
        val allFixes = mutableListOf<String>()
        val updatedFiles = mutableListOf<BotFile>()

        // 1. Auto-fix each existing file
        for (file in files) {
            val result = autoFixFile(file.content, file.filePath, project)
            if (result.wasModified) {
                allFixes.addAll(result.fixesApplied.map { "[${file.filePath}] $it" })
                updatedFiles.add(file.copy(content = result.fixedCode, updatedAt = System.currentTimeMillis()))
            } else {
                updatedFiles.add(file)
            }
        }

        var addedCount = 0
        val isPython = project.language.equals(BotLanguage.PYTHON.name, ignoreCase = true) ||
                files.any { it.filePath.endsWith(".py", ignoreCase = true) }

        // 2. Ensure an entrypoint file exists and is active
        val hasEntrypoint = updatedFiles.any { it.isEntrypoint }
        if (!hasEntrypoint && updatedFiles.isNotEmpty()) {
            val candidate = updatedFiles.find {
                it.filePath in listOf("index.js", "bot.js", "main.js", "bot.py", "main.py", "src/index.ts")
            } ?: updatedFiles.first()
            val idx = updatedFiles.indexOf(candidate)
            updatedFiles[idx] = candidate.copy(isEntrypoint = true)
            allFixes.add("Set '${candidate.filePath}' as main bot entrypoint")
        }

        // 3. Auto-generate .env if missing
        if (updatedFiles.none { it.filePath.equals(".env", ignoreCase = true) }) {
            val token = project.botToken.ifBlank { "MTE4OTIzNDU2Nzg5MDEyMzQ1Ng.G-DiscordSecretBotTokenHere" }
            val envContent = StringBuilder()
                .append("# Discord Bot Environment Variables (Auto-generated by BotStudio)\n")
                .append("DISCORD_TOKEN=").append(token).append("\n")
                .append("CLIENT_ID=").append(project.clientId.ifBlank { "118923456789012345" }).append("\n")
                .append("PREFIX=").append(project.prefix.ifBlank { "!" }).append("\n")
                .toString()

            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = ".env",
                    content = envContent,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created '.env' file with token and prefix variables")
            addedCount++
        }

        // 4. Auto-generate package.json for JS/TS if missing
        if (!isPython && updatedFiles.none { it.filePath.equals("package.json", ignoreCase = true) }) {
            val safeName = project.name.lowercase().replace(" ", "-").filter { it.isLetterOrDigit() || it == '-' }
            val pkgJson = """
{
  "name": "${safeName.ifBlank { "discord-bot" }}",
  "version": "1.0.0",
  "description": "${project.description}",
  "main": "index.js",
  "scripts": {
    "start": "node index.js",
    "dev": "nodemon index.js"
  },
  "dependencies": {
    "discord.js": "^14.14.1",
    "dotenv": "^16.4.5"
  },
  "engines": {
    "node": ">=18.0.0"
  }
}
""".trimIndent()

            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = "package.json",
                    content = pkgJson,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created 'package.json' configured for Discord.js v14+")
            addedCount++
        }

        // 5. Auto-generate requirements.txt for Python if missing
        if (isPython && updatedFiles.none { it.filePath.equals("requirements.txt", ignoreCase = true) }) {
            val reqContent = """
# Python Discord Bot Dependencies (Auto-generated by BotStudio)
discord.py>=2.3.2
python-dotenv>=1.0.0
requests>=2.31.0
""".trimIndent()

            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = "requirements.txt",
                    content = reqContent,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created 'requirements.txt' with discord.py 2.0+ requirements")
            addedCount++
        }

        // 6. Auto-generate README.md with run instructions if missing
        if (updatedFiles.none { it.filePath.equals("README.md", ignoreCase = true) }) {
            val readmeContent = generateReadme(project, isPython)
            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = "README.md",
                    content = readmeContent,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created 'README.md' with quick-start and deployment guide")
            addedCount++
        }

        // 7. Auto-generate .gitignore if missing
        if (updatedFiles.none { it.filePath.equals(".gitignore", ignoreCase = true) }) {
            val gitignoreContent = """
# Discord Bot .gitignore (Auto-generated by BotStudio)
node_modules/
.env
__pycache__/
*.pyc
*.pyo
dist/
build/
*.log
.DS_Store
""".trimIndent()
            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = ".gitignore",
                    content = gitignoreContent,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created '.gitignore' to protect sensitive tokens and secrets")
            addedCount++
        }

        // 8. Auto-generate Procfile for instant cloud deployment (Railway / Heroku / Render)
        if (updatedFiles.none { it.filePath.equals("Procfile", ignoreCase = true) }) {
            val entryCandidate = updatedFiles.find { it.isEntrypoint }?.filePath ?: if (isPython) "bot.py" else "index.js"
            val procContent = if (isPython) "worker: python $entryCandidate\n" else "worker: node $entryCandidate\n"
            updatedFiles.add(
                BotFile(
                    projectId = project.id,
                    filePath = "Procfile",
                    content = procContent,
                    isEntrypoint = false,
                    updatedAt = System.currentTimeMillis()
                )
            )
            allFixes.add("Auto-created 'Procfile' for 1-click cloud bot deployment")
            addedCount++
        }

        return ProjectAutoFixReport(
            updatedFiles = updatedFiles,
            fixesApplied = allFixes,
            addedFileCount = addedCount
        )
    }

    private fun fixJavaScriptDiscordCode(
        raw: String,
        filePath: String,
        project: BotProject?
    ): AutoFixResult {
        var code = raw.trim()
        val fixes = mutableListOf<String>()

        // 1. If file is completely empty or just comments, generate a complete working Discord.js v14 bot
        if (code.isBlank() || code.lines().all { it.trim().startsWith("//") || it.trim().startsWith("/*") || it.isBlank() }) {
            val prefix = project?.prefix?.ifBlank { "!" } ?: "!"
            val botName = project?.name ?: "Discord Bot"
            val token = project?.botToken?.ifBlank { "YOUR_BOT_TOKEN_HERE" } ?: "YOUR_BOT_TOKEN_HERE"

            val template = """
// 🤖 $botName - Discord.js v14 Bot
// Generated & Prepared by BotStudio
require('dotenv').config();
const { Client, GatewayIntentBits, Partials, EmbedBuilder, ActivityType } = require('discord.js');

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers
  ],
  partials: [Partials.Channel, Partials.Message]
});

const PREFIX = process.env.PREFIX || '$prefix';

// Bot Ready Event
client.once('ready', (c) => {
  console.log(`🤖 Logged in as ${'$'}{c.user.tag}! Bot is ready.`);
  c.user.setActivity(`${'$'}{PREFIX}help | Online`, { type: ActivityType.Playing });
});

// Message Command Handler
client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  if (!message.content.startsWith(PREFIX)) return;

  const args = message.content.slice(PREFIX.length).trim().split(/ +/);
  const command = args.shift().toLowerCase();

  // Ping Command
  if (command === 'ping') {
    const sent = await message.reply('🏓 Pinging...');
    const latency = sent.createdTimestamp - message.createdTimestamp;
    await sent.edit(`🏓 Pong! Latency is ${'$'}{latency}ms | API: ${'$'}{Math.round(client.ws.ping)}ms`);
  }

  // Help Command
  else if (command === 'help') {
    const embed = new EmbedBuilder()
      .setTitle('🤖 Bot Commands')
      .setColor('#5865F2')
      .setDescription(`Commands available for **${'$'}{client.user.username}**:`)
      .addFields(
        { name: `${'$'}{PREFIX}ping`, value: 'Check bot gateway latency and responsiveness', inline: true },
        { name: `${'$'}{PREFIX}help`, value: 'Display this interactive command menu', inline: true },
        { name: `${'$'}{PREFIX}info`, value: 'View server and bot runtime information', inline: true }
      )
      .setFooter({ text = 'BotStudio Discord Bot Engine' })
      .setTimestamp();

    await message.reply({ embeds: [embed] });
  }

  // Info Command
  else if (command === 'info') {
    await message.reply(`ℹ️ **${'$'}{client.user.username}** is running Discord.js v14 on BotStudio! Guilds: ${'$'}{client.guilds.cache.size}`);
  }
});

// Login to Discord Gateway
const TOKEN = process.env.DISCORD_TOKEN || '$token';
client.login(TOKEN).catch((err) => {
  console.error('❌ Failed to login to Discord:', err.message);
});
""".trimIndent()

            return AutoFixResult(
                fixedCode = template,
                fixesApplied = listOf("Generated complete, active Discord.js v14 bot template with !ping and !help"),
                wasModified = true
            )
        }

        // 2. Fix Deprecated MessageEmbed -> EmbedBuilder
        if (code.contains("MessageEmbed")) {
            code = code.replace("new Discord.MessageEmbed()", "new EmbedBuilder()")
                .replace("new MessageEmbed()", "new EmbedBuilder()")
            fixes.add("Upgraded deprecated MessageEmbed to Discord.js v14 EmbedBuilder")
        }

        // 3. Fix Deprecated 'message' event -> 'messageCreate'
        if (Regex("""\.on\(\s*['"]message['"]\s*,""").containsMatchIn(code)) {
            code = code.replace(Regex("""\.on\(\s*['"]message['"]\s*,"""), ".on('messageCreate',")
            fixes.add("Upgraded deprecated 'message' event to 'messageCreate'")
        }

        // 4. Ensure modern Discord.js imports and GatewayIntentBits
        val hasDiscordRequire = code.contains("require('discord.js')") || code.contains("require(\"discord.js\")")
        val hasDiscordImport = code.contains("from 'discord.js'") || code.contains("from \"discord.js\"")

        if (hasDiscordRequire || hasDiscordImport) {
            // Check if Client instantiation is missing intents
            val clientRegex = Regex("""new\s+(?:Discord\.)?Client\(\s*\{?([^)]*)\}?\s*\)""")
            val match = clientRegex.find(code)
            if (match != null) {
                val currentArgs = match.groupValues[1]
                if (!currentArgs.contains("GatewayIntentBits") && !currentArgs.contains("intents")) {
                    val modernClientInit = """new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers
  ],
  partials: [Partials.Channel, Partials.Message]
})"""
                    code = code.replace(match.value, modernClientInit)
                    fixes.add("Upgraded Client to modern Discord.js v14 GatewayIntentBits (Guilds, Messages, MessageContent)")
                }
            }

            // Ensure required destructured symbols are imported
            if (code.contains("const Discord = require('discord.js')") || code.contains("const Discord = require(\"discord.js\")")) {
                code = code.replace(
                    Regex("""const\s+Discord\s*=\s*require\(['"]discord\.js['"]\);?"""),
                    "const { Client, GatewayIntentBits, Partials, EmbedBuilder, ActivityType } = require('discord.js');\nconst Discord = require('discord.js');"
                )
                fixes.add("Added GatewayIntentBits and EmbedBuilder imports from discord.js")
            }
        }

        // 5. Add Bot Self-Response Guard in messageCreate if missing
        if (code.contains("messageCreate") && !code.contains("message.author.bot") && !code.contains("msg.author.bot")) {
            val handlerRegex = Regex("""(client\.on\(\s*['"]messageCreate['"]\s*,\s*(?:async\s*)?(?:\([^)]*\)|[a-zA-Z0-9_]+)\s*=>\s*\{)""")
            if (handlerRegex.containsMatchIn(code)) {
                code = code.replace(handlerRegex) { m ->
                    "${m.value}\n  if (message.author.bot) return;"
                }
                fixes.add("Added bot self-response guard (if (message.author.bot) return)")
            }
        }

        // 5b. Secure hardcoded bot tokens into process.env.DISCORD_TOKEN
        val hardcodedTokenRegex = Regex("""client\.login\(\s*["']([A-Za-z0-9_\-\.]{40,})["']\s*\)""")
        val tokenMatch = hardcodedTokenRegex.find(code)
        if (tokenMatch != null) {
            val tokenStr = tokenMatch.groupValues[1]
            code = code.replace(tokenMatch.value, "client.login(process.env.DISCORD_TOKEN || '$tokenStr')")
            fixes.add("Secured hardcoded bot token into environment variable process.env.DISCORD_TOKEN")
        }

        // 5c. Ensure require('dotenv').config() is at top if process.env is used
        if (code.contains("process.env") && !code.contains("dotenv")) {
            code = "require('dotenv').config();\n" + code
            fixes.add("Injected 'require(\"dotenv\").config()' for environment configuration")
        }

        // 5d. Modernize collection cache lookups (client.channels.get -> client.channels.cache.get)
        val cacheReplacements = listOf(
            Regex("""client\.channels\.get\(""") to "client.channels.cache.get(",
            Regex("""client\.guilds\.get\(""") to "client.guilds.cache.get(",
            Regex("""client\.users\.get\(""") to "client.users.cache.get(",
            Regex("""(?:message|msg)\.guild\.roles\.get\(""") to "message.guild.roles.cache.get(",
            Regex("""(?:message|msg)\.guild\.members\.get\(""") to "message.guild.members.cache.get(",
            Regex("""(?:message|msg)\.guild\.channels\.get\(""") to "message.guild.channels.cache.get("
        )
        for ((pattern, replacement) in cacheReplacements) {
            if (pattern.containsMatchIn(code)) {
                code = code.replace(pattern, replacement)
                fixes.add("Updated deprecated cache collection method to modern '.cache.get()'")
            }
        }

        // 5e. Auto-add interactive starter commands router if client exists but has no command handlers
        val isEntry = filePath.endsWith("index.js") || filePath.endsWith("bot.js") || filePath.endsWith("main.js")
        if (isEntry && code.contains("client.") && !code.contains("messageCreate") && !code.contains("interactionCreate")) {
            val prefix = project?.prefix?.ifBlank { "!" } ?: "!"
            val commandsSnippet = """

// Auto-added by BotStudio: Interactive Command Router
client.on('messageCreate', async (message) => {
  if (message.author.bot) return;
  const prefix = process.env.PREFIX || '$prefix';
  if (!message.content.startsWith(prefix)) return;

  const args = message.content.slice(prefix.length).trim().split(/ +/);
  const command = args.shift().toLowerCase();

  if (command === 'ping') {
    const sent = await message.reply('🏓 Pinging...');
    const latency = sent.createdTimestamp - message.createdTimestamp;
    await sent.edit(`🏓 Pong! Latency: ${'$'}{latency}ms | Gateway API: ${'$'}{Math.round(client.ws.ping)}ms`);
  } else if (command === 'help') {
    await message.reply(`🤖 **Bot is Active!** Available commands:\n• \`${'$'}{prefix}ping\` - Check bot latency\n• \`${'$'}{prefix}info\` - Bot status info\n• \`${'$'}{prefix}help\` - Show this help menu`);
  } else if (command === 'info') {
    await message.reply(`ℹ️ Running on BotStudio Discord Engine! Guilds: ${'$'}{client.guilds.cache.size}`);
  }
});
"""
            val insertPos = if (code.contains("client.login")) code.indexOf("client.login") else code.length
            code = code.substring(0, insertPos) + commandsSnippet + "\n" + code.substring(insertPos)
            fixes.add("Added interactive starter commands (!ping, !help, !info) to make bot immediately active")
        }

        // 6. Add client.login() if missing in entrypoint file
        if (isEntry && !code.contains("client.login") && !code.contains(".login(")) {
            val token = project?.botToken?.ifBlank { "YOUR_BOT_TOKEN_HERE" } ?: "YOUR_BOT_TOKEN_HERE"
            val loginSnippet = """

// Auto-added by BotStudio: Start the Discord Bot
const BOT_TOKEN = process.env.DISCORD_TOKEN || '$token';
client.login(BOT_TOKEN).then(() => {
  console.log('🤖 Bot successfully logged in to Discord Gateway!');
}).catch(err => {
  console.error('❌ Failed to login to Discord:', err.message);
});
"""
            code += loginSnippet
            fixes.add("Added missing client.login() with token connection")
        }

        // 7. Add client.once('ready') if missing in entrypoint file
        if (isEntry && !code.contains("ready") && code.contains("client.")) {
            val readySnippet = """

client.once('ready', (c) => {
  console.log(`🤖 Logged in as ${'$'}{c.user.tag}! Bot is online.`);
});
"""
            val insertIdx = code.indexOf("client.login")
            if (insertIdx != -1) {
                code = code.substring(0, insertIdx) + readySnippet + "\n" + code.substring(insertIdx)
            } else {
                code += readySnippet
            }
            fixes.add("Added missing client.once('ready') status listener")
        }

        // 8. Auto-balance unclosed braces / parentheses
        val openBraces = code.count { it == '{' }
        val closeBraces = code.count { it == '}' }
        if (openBraces > closeBraces) {
            val diff = openBraces - closeBraces
            code += "\n" + "}".repeat(diff)
            fixes.add("Auto-balanced $diff missing closing brace${if (diff > 1) "s" else ""}")
        }

        val openParens = code.count { it == '(' }
        val closeParens = code.count { it == ')' }
        if (openParens > closeParens) {
            val diff = openParens - closeParens
            code += ")".repeat(diff)
            fixes.add("Auto-balanced $diff missing closing parenthesis")
        }

        return AutoFixResult(
            fixedCode = code,
            fixesApplied = fixes,
            wasModified = fixes.isNotEmpty()
        )
    }

    private fun fixPythonDiscordCode(
        raw: String,
        filePath: String,
        project: BotProject?
    ): AutoFixResult {
        var code = raw.trim()
        val fixes = mutableListOf<String>()

        // 1. If file is empty, generate complete working discord.py 2.0+ bot
        if (code.isBlank() || code.lines().all { it.trim().startsWith("#") || it.isBlank() }) {
            val prefix = project?.prefix?.ifBlank { "!" } ?: "!"
            val botName = project?.name ?: "Discord Bot"
            val token = project?.botToken?.ifBlank { "YOUR_BOT_TOKEN_HERE" } ?: "YOUR_BOT_TOKEN_HERE"

            val template = """
# 🤖 $botName - discord.py 2.0+ Bot
# Generated & Prepared by BotStudio
import os
import discord
from discord.ext import commands
from dotenv import load_dotenv

load_dotenv()

# Configure mandatory Discord Gateway Intents
intents = discord.Intents.default()
intents.message_content = True
intents.guilds = True

PREFIX = os.getenv('PREFIX', '$prefix')
bot = commands.Bot(command_prefix=PREFIX, intents=intents)

@bot.event
async def on_ready():
    print(f'🤖 Logged in as {bot.user} (ID: {bot.user.id})')
    print('Bot is online and ready to receive commands!')
    await bot.change_presence(activity=discord.Game(name=f"{PREFIX}help | Online"))

@bot.command(name='ping')
async def ping(ctx):
    latency = round(bot.latency * 1000)
    await ctx.send(f'🏓 Pong! Latency: {latency}ms')

@bot.command(name='info')
async def info(ctx):
    embed = discord.Embed(
        title="🤖 Bot Information",
        description=f"Running **discord.py** on BotStudio!",
        color=discord.Color.blue()
    )
    embed.add_field(name="Servers", value=str(len(bot.guilds)), inline=True)
    embed.add_field(name="Prefix", value=PREFIX, inline=True)
    embed.set_footer(text="BotStudio Discord Runtime")
    await ctx.send(embed=embed)

# Start the bot
TOKEN = os.getenv('DISCORD_TOKEN', '$token')
bot.run(TOKEN)
""".trimIndent()

            return AutoFixResult(
                fixedCode = template,
                fixesApplied = listOf("Generated complete, active discord.py 2.0+ bot with !ping and !info"),
                wasModified = true
            )
        }

        // 2. Fix missing message_content intent
        if (code.contains("commands.Bot(") || code.contains("commands.Bot (")) {
            if (!code.contains("intents") || !code.contains("message_content")) {
                val intentsSnippet = """
# Configure mandatory Discord Gateway Intents (discord.py 2.0+)
intents = discord.Intents.default()
intents.message_content = True
intents.guilds = True
"""
                val importIdx = code.indexOf("commands.Bot")
                if (importIdx != -1) {
                    val lineStart = code.lastIndexOf('\n', importIdx).coerceAtLeast(0)
                    code = code.substring(0, lineStart) + intentsSnippet + "\n" + code.substring(lineStart)
                    code = code.replace(
                        Regex("""commands\.Bot\(\s*command_prefix\s*=\s*([^,)]+)"""),
                        "commands.Bot(command_prefix=$1, intents=intents"
                    )
                    fixes.add("Injected mandatory discord.Intents with message_content = True")
                }
            }
        }

        // 3. Remove deprecated pass_context=True
        if (code.contains("pass_context=True") || code.contains("pass_context = True")) {
            code = code.replace(Regex("""pass_context\s*=\s*True,?\s*"""), "")
            fixes.add("Removed deprecated pass_context=True parameter")
        }

        // 3b. Secure hardcoded bot tokens in bot.run("...")
        val pyTokenRegex = Regex("""(?:bot|client)\.run\(\s*["']([A-Za-z0-9_\-\.]{40,})["']\s*\)""")
        val pyTokenMatch = pyTokenRegex.find(code)
        if (pyTokenMatch != null) {
            val tokenStr = pyTokenMatch.groupValues[1]
            code = code.replace(pyTokenMatch.value, "TOKEN = os.getenv('DISCORD_TOKEN', '$tokenStr')\nbot.run(TOKEN)")
            fixes.add("Secured hardcoded bot token into environment variable os.getenv('DISCORD_TOKEN')")
        }

        // 3c. Ensure load_dotenv() is present if os.getenv or .env is referenced
        if (code.contains("os.getenv") && !code.contains("load_dotenv")) {
            code = "import os\nfrom dotenv import load_dotenv\nload_dotenv()\n\n" + code
            fixes.add("Injected 'from dotenv import load_dotenv' to load bot credentials")
        }

        // 3d. Fix on_message overriding without process_commands
        if (code.contains("async def on_message(") && !code.contains("process_commands")) {
            val onMessageRegex = Regex("""(async\s+def\s+on_message\s*\([^)]*\)\s*:\s*\n)([\s\S]*?)(\n\s*(?:@|def\s+|async\s+def\s+|bot\.run|client\.run|$))""")
            val match = onMessageRegex.find(code)
            if (match != null) {
                val fullBody = match.groupValues[2]
                val indent = fullBody.lines().firstOrNull { it.isNotBlank() }?.takeWhile { it == ' ' } ?: "    "
                val updatedBody = fullBody.trimEnd() + "\n$indent# Auto-added: Ensure commands still process\n${indent}await bot.process_commands(message)\n"
                code = code.replaceRange(match.range, "${match.groupValues[1]}$updatedBody${match.groupValues[3]}")
                fixes.add("Injected 'await bot.process_commands(message)' into on_message so commands execute properly")
            }
        }

        // 4. Add bot.run() if missing in entrypoint file
        val isEntry = filePath.endsWith("bot.py") || filePath.endsWith("main.py") || filePath.endsWith("app.py")
        if (isEntry && !code.contains("bot.run(") && !code.contains("client.run(")) {
            val token = project?.botToken?.ifBlank { "YOUR_BOT_TOKEN_HERE" } ?: "YOUR_BOT_TOKEN_HERE"
            code += """

# Auto-added by BotStudio: Start the Discord Bot
import os
TOKEN = os.getenv('DISCORD_TOKEN', '$token')
bot.run(TOKEN)
"""
            fixes.add("Added missing bot.run(TOKEN) execution call")
        }

        // 5. Add on_ready event if missing
        if (isEntry && !code.contains("on_ready") && code.contains("bot =")) {
            val onReadySnippet = """

@bot.event
async def on_ready():
    print(f'🤖 Logged in as {bot.user} (ID: {bot.user.id})')
    print('Bot is active and ready to handle commands!')
"""
            val runIdx = code.indexOf("bot.run")
            if (runIdx != -1) {
                code = code.substring(0, runIdx) + onReadySnippet + "\n" + code.substring(runIdx)
            } else {
                code += onReadySnippet
            }
            fixes.add("Added missing @bot.event on_ready handler")
        }

        // 6. Auto-add starter commands if no commands exist
        if (isEntry && !code.contains("@bot.command") && !code.contains("@client.command") && code.contains("bot =")) {
            val starterCmds = """

# Auto-added by BotStudio: Starter Commands
@bot.command(name='ping')
async def ping(ctx):
    latency = round(bot.latency * 1000)
    await ctx.send(f'🏓 Pong! Latency: {latency}ms')

@bot.command(name='info')
async def info(ctx):
    await ctx.send(f'🤖 **{bot.user.name}** is online and running on BotStudio!')
"""
            val runIdx = code.indexOf("bot.run")
            if (runIdx != -1) {
                code = code.substring(0, runIdx) + starterCmds + "\n" + code.substring(runIdx)
            } else {
                code += starterCmds
            }
            fixes.add("Added starter commands (!ping, !info) to make bot immediately active")
        }

        return AutoFixResult(
            fixedCode = code,
            fixesApplied = fixes,
            wasModified = fixes.isNotEmpty()
        )
    }

    private fun fixJsonCode(raw: String): AutoFixResult {
        val fixes = mutableListOf<String>()
        val formatted = try {
            org.json.JSONObject(raw).toString(2)
        } catch (_: Exception) {
            try {
                org.json.JSONArray(raw).toString(2)
            } catch (_: Exception) {
                raw
            }
        }
        if (formatted != raw && formatted.isNotBlank()) {
            fixes.add("Formatted and validated JSON structure")
        }
        return AutoFixResult(
            fixedCode = formatted,
            fixesApplied = fixes,
            wasModified = fixes.isNotEmpty()
        )
    }

    private fun fixEnvCode(raw: String, project: BotProject?): AutoFixResult {
        var code = raw.trim()
        val fixes = mutableListOf<String>()

        if (!code.contains("DISCORD_TOKEN")) {
            val token = project?.botToken?.ifBlank { "YOUR_BOT_TOKEN_HERE" } ?: "YOUR_BOT_TOKEN_HERE"
            code += "\nDISCORD_TOKEN=$token\n"
            fixes.add("Added missing DISCORD_TOKEN key")
        }
        if (!code.contains("PREFIX")) {
            val prefix = project?.prefix?.ifBlank { "!" } ?: "!"
            code += "PREFIX=$prefix\n"
            fixes.add("Added missing PREFIX key")
        }

        return AutoFixResult(
            fixedCode = code,
            fixesApplied = fixes,
            wasModified = fixes.isNotEmpty()
        )
    }

    private fun generateReadme(project: BotProject, isPython: Boolean): String {
        return """
# 🤖 ${project.name}

${project.description}

This Discord Bot was developed and prepared with **BotStudio**.

---

## 🚀 Quick Start Guide

### 1. Configure Bot Token
Ensure your Discord Bot Token is added in the `.env` file:
```env
DISCORD_TOKEN=your_token_here
PREFIX=${project.prefix}
```

### 2. Required Discord Gateway Intents
In the [Discord Developer Portal](https://discord.com/developers/applications):
1. Go to your Application -> **Bot** tab.
2. Under **Privileged Gateway Intents**, enable:
   - ✅ **Message Content Intent** (Required for commands)
   - ✅ **Server Members Intent** (Optional, for join/leave events)
   - ✅ **Presence Intent** (Optional)

### 3. Run the Bot
${if (isPython) """
```bash
# Install dependencies
pip install -r requirements.txt

# Run the bot
python bot.py
```
""" else """
```bash
# Install dependencies
npm install

# Start the bot
npm start
```
"""}

---
*Created with BotStudio on Android.*
""".trimIndent()
    }
}
