name: Mobile APK Builder
on: [push, workflow_dispatch] # Allows automatic and manual triggers

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions
        run: chmod +x gradlew

      - name: Build Android Debug APK
        run: ./gradlew assembleDebug

      - name: Save and Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/*.apk
